name: first
on: 
  push:
    branches:
      - master
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: run date cmd
        run: date
  window:
    runs-on: windows-latest
    steps:
      - name: run date cmd
        run: date
  macos:
    runs-on: macos-latest
    steps:
      - name: run date cmd
        run: date
  depends:
    needs: [ubuntu, window, macos]
    runs-on: macos-10.15
    steps:
      - run: date
  list:
    needs: depends
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -ltr
          java -version

