name: first
on: 
  push:
    branches:
      - master
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: run date cmd
        run: date
  window:
    runs-on: windows-latest
    steps:
      - name: run date cmd
        run: date
  macos:
    needs: ubuntu
    runs-on: macos-latest
    steps:
      - name: run date cmd
        run: date

